# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [9]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [10]:
cities = pd.read_csv("../WeatherPy/output_data/cities_csv.csv")
cities = cities.drop(columns=['Unnamed: 0'])
cities.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Abramovka,51.19,41.02,62.51,30,100,20.45,RU,1601447405
1,Abu Dhabi,24.47,54.37,95.00,17,0,11.41,AE,1601447405
2,Abu Kamal,34.45,40.92,88.84,22,0,8.25,SY,1601447406
3,Acaraú,-2.89,-40.12,78.69,73,87,16.75,BR,1601447406
4,Adrar,20.50,-10.07,84.90,29,0,10.74,MR,1601447407

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [ ]:
gmaps.configure(api_key='g_key')

In [11]:
locations=cities[['Lat','Lng']]
humidity = cities['Humidity']

fig=gmaps.figure()
heatmap = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity=10, point_radius=1)
fig.add_layer(heatmap)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [12]:
#filter cities for temp between 60 and 75, wind speed less than 20 mph, cloudiness close to 0, humidity less then 50%
ideal_cities = cities.loc[(cities['Max Temp']>=60) & (cities['Max Temp']<=75)&(cities['Wind Speed']<=20)&(cities['Cloudiness']<=10)&(cities['Humidity']<=50)]
ideal_cities

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
85,Bom Jesus,-9.07,-44.36,72.46,46,0,2.68,BR,1601447467
130,Chingirlau,51.09,54.08,64.62,39,0,8.86,KZ,1601447481
189,Frontera,26.93,-101.45,68.00,32,0,1.99,MX,1601447499
202,Geraldton,-28.77,114.60,73.40,49,0,12.75,AU,1601447468
218,Kumul,42.80,93.45,61.41,26,0,1.23,CN,1601447508
293,Khorixas,-20.37,14.97,69.91,22,0,3.80,NaN,1601447534
306,Korla,41.76,86.15,60.40,30,0,6.58,CN,1601447295
384,Matamoros,25.53,-103.25,64.99,50,0,1.90,MX,1601447561
469,Perevolotskiy,51.88,54.19,61.70,46,0,10.27,RU,1601447588
482,Lüshunkou,38.80,121.27,66.20,34,0,13.42,CN,1601447592
531,Saint George,37.10,-113.58,69.01,14,1,4.70,US,1601447462
547,San Martín,-33.08,-68.47,64.40,22,0,5.82,AR,1601447612
569,Semnan,35.57,53.40,64.51,29,0,7.38,IR,1601447619
631,Torbat-e Jām,35.24,60.62,61.12,27,0,2.30,IR,1601447639
651,Ukiah,39.15,-123.21,69.80,40,1,1.88,US,1601447402
664,Villamontes,-21.25,-63.50,73.15,49,0,4.36,BO,1601447651
689,Yumen,40.28,97.20,63.27,28,0,13.51,CN,1601447659

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [15]:
target_type='hotel'
radius = 5000
target_search = 'hotel'
url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

Latitude = ideal_cities['Lat']
Longitude = ideal_cities['Lng']
hotel_names=[]

for city, row in ideal_cities.iterrows():
    Latitude = row['Lat']
    Longitude = row['Lng']

    target_coordinates = f'{Latitude},{Longitude}'
    params={
        "location": target_coordinates,
        "keyword": target_search,
        "radius": radius,
        "type": target_type,
        "key": g_key
    }
    
    response = requests.get(url, params=params).json()
    try:
        hotel_names.append(response['results'][0]['name'])
    except:
        hotel_names.append('N/A')
    

ideal_cities['Hotel Name'] = hotel_names
ideal_cities

C:\Users\Travis Molnoskey\.conda\envs\pythondata\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
85,Bom Jesus,-9.07,-44.36,72.46,46,0,2.68,BR,1601447467,Gurguéia Palace Hotel
130,Chingirlau,51.09,54.08,64.62,39,0,8.86,KZ,1601447481,N/A
189,Frontera,26.93,-101.45,68.00,32,0,1.99,MX,1601447499,Holiday Inn Monclova
202,Geraldton,-28.77,114.60,73.40,49,0,12.75,AU,1601447468,The Gerald Apartment Hotel
218,Kumul,42.80,93.45,61.41,26,0,1.23,CN,1601447508,哈密环球大酒店
293,Khorixas,-20.37,14.97,69.91,22,0,3.80,NaN,1601447534,iGowati Lodge
306,Korla,41.76,86.15,60.40,30,0,6.58,CN,1601447295,Kangcheng Jian Guo International Hotel
384,Matamoros,25.53,-103.25,64.99,50,0,1.90,MX,1601447561,HOTEL PLAZA MATAMOROS
469,Perevolotskiy,51.88,54.19,61.70,46,0,10.27,RU,1601447588,GRAND OASIS
482,Lüshunkou,38.80,121.27,66.20,34,0,13.42,CN,1601447592,Yilv Yangguang Hotel
531,Saint George,37.10,-113.58,69.01,14,1,4.70,US,1601447462,Inn on The Cliff St. George
547,San Martín,-33.08,-68.47,64.40,22,0,5.82,AR,1601447612,Cabañas Plaza Norte
569,Semnan,35.57,53.40,64.51,29,0,7.38,IR,1601447619,Semnan Traditional Hotel
631,Torbat-e Jām,35.24,60.62,61.12,27,0,2.30,IR,1601447639,Pardisan Hotel 🏩
651,Ukiah,39.15,-123.21,69.80,40,1,1.88,US,1601447402,Hampton Inn Ukiah
664,Villamontes,-21.25,-63.50,73.15,49,0,4.36,BO,1601447651,Hotel El Rancho
689,Yumen,40.28,97.20,63.27,28,0,13.51,CN,1601447659,N/A

In [16]:
hotel_df = ideal_cities

In [17]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [18]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))